'''

@Author: Jayesh Patil

@Date: 2024-08-26

@Last Modified by: Jayesh Patil

@Title: NumPy Programs 

'''

In [1]:
import numpy as np

1.Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.

In [2]:
def list_to_numpy_array(input_list):
    """
        Discription :
            Converts a list of numerical values into a NumPy array.
    
        Parameters:
            input_list (list): A list containing numerical values.
        
        Return:
            numpy.nparray: A NumPy array representation of the input list.
    """
    return np.array(input_list)

def main():
    list1 = [12.23, 13.32, 100, 36.32]
    result_array = list_to_numpy_array(list1)
    print("This is numpy array:", result_array)

if __name__ == "__main__":
    main()


This is numpy array: [ 12.23  13.32 100.    36.32]


2.Create a 3x3 matrix with values ranging from 2 to 10.

In [3]:
def create_matrix():
    """
        Discription :
            Create a 3x3 matrix with the values range from 2 to 10.
    
        Parameters:
            None
        
        Return:
            numpy.matrix: A NumPy matrix representation .
    """    

    matrix = np.matrix([[2,3,4],[5,6,7],[8,9,10]])
    return matrix
def main():
    matrix = create_matrix()
    print(f"The matrix is {matrix}")
if __name__=="__main__":
    main()        

The matrix is [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3.Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [5]:
 def create_and_update_vector():
    """
        Discription :
            Creates a null vector (array of zeros) of size 10 and updates the sixth value to 11.
        Parameters :
            None    
    
        Returns:
            The updated vector with the sixth value set to 11.
    """
   
    vector = np.zeros(10)
    
    
    vector[5] = 11
    
    return vector

def main():
    vector = create_and_update_vector()
    print("Original vector:",np.zeros(10))
    print("Updated vector:",vector)
    

if __name__ == "__main__":
    main()    



Original vector: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated vector: [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


4.Python program to reverse an array (first element becomes last).

In [6]:
def reverse_array(arr):
    """
        Discription :
            Reverses the order of elements in the given array.

        Parameters:
            arr (numpy.ndarray): The array to be reversed.
        
        Returns:
            numpy.ndarray: The reversed array.
    """
    return arr[::-1]
def main():
    Original_array= np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37])
    print("Original_array",Original_array)

    reversed_array = reverse_array(Original_array)
    print("Reverse_array",reversed_array)
if __name__ == "__main__":
    main()      
    


Original_array [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse_array [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5.Python program to create a 2d array with 1 on the border and 0 inside.

In [7]:
def create_border_array(size):
    """
        Discription :
            Creates a 2D array of given size with 1 on the border and 0 inside.

        Parameters:
            size (int): The size of the 2D array (it will be size x size).
        
        Returns:
            numpy.ndarray: A 2D array with 1 on the borders and 0 inside.
    """
    
    array = np.ones((size, size))
    
    
    array[1:-1, 1:-1] = 0
    
    return array

def main():
    size = 5 
    original_array = np.ones((size, size))
    print("Original array:")
    print(original_array)
    
    border_array = create_border_array(size)
    print("1 on the border and 0 inside in the array:")
    print(border_array)

if __name__ == "__main__":
    main()


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6.Python program to add a border (filled with 0's) around an existing array.

In [8]:
def create_border_array(size):
    """
        Discription :
            Adds a border of zeros around an existing 2D array

        Parameters:
            size (int): The size of the 2D array (it will be size x size).
        
        Returns:
            A 2D array with 1 on the borders and 0 inside.
    """
    array = np.zeros((size+2,size+2))
    array[1:-1, 1:-1] = 1
    
    return array
def main():
    size = 3
    original_array = np.ones((size,size))
    print("original array:",original_array)

    border_array = create_border_array(size)
    print("0 on the border ",border_array)
if __name__ == "__main__":
    main()        

original array: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border  [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7.Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [9]:
def checkerboard_pattern(size):
    """
        Discription :
            This programs is checkerboard pattern

        Parameters:
            size (int): The size of the 2D array (it will be size x size).
        
        Returns:
            A 2D array with 1 on the borders and 0 inside.
    """
    array = np.ones((size,size))
    array[1::2,::2] = 0
    array[::2,1::2] = 0
    return array
def main():
    size = 8
    array = checkerboard_pattern(size)
    print("Checker board pattern :\n",array)
if __name__ == "__main__":
    main()    
        

Checker board pattern :
 [[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


8.Python program to convert a list and tuple into arrays.

In [10]:
def convert_to_array(data):
    """
        Discription :
            Converts a list or tuple into a NumPy array.

        Parameters:
            data (list or tuple): The list or tuple to be converted.
        
        Returns:
            The converted NumPy array
    """
    return np.array(data)
def main():
    list1 = [21,22,23.24]
    tuple1 = (31,32,33,34) 
    list_array = convert_to_array(list1)
    print("original list :",list1)
    print("Converted array from list:",list_array)

    tuple_array = convert_to_array(tuple1)
    print("original tuple :",tuple1)
    print("converted array from tuple :",tuple_array)

if __name__=="__main__":
    main()          

original list : [21, 22, 23.24]
Converted array from list: [21.   22.   23.24]
original tuple : (31, 32, 33, 34)
converted array from tuple : [31 32 33 34]


9.Python program to append values to the end of an array.

In [11]:
def append_to_array(arr,values):
    """
        Discription :
            Appends values to the given NumPy array.

        Parameters:
            array (numpy.ndarray): The original array.
            values (list or numpy.ndarray): The values to append to the array.
        
        Returns:
            A new array with the appended values.
    """
    return np.append(arr,values)
def main():
    Original_array = [10, 20, 30]
    append_array = append_to_array(Original_array,[40,50,60,70,80])
    print("Original array :",Original_array)
    print("appended array :",append_array)   
if __name__ == "__main__":
    main()     

Original array : [10, 20, 30]
appended array : [10 20 30 40 50 60 70 80]


10.Python program to find the real and imaginary parts of an array of complex numbers.

In [12]:
def extract_real_imag_part(complex_array):
    """
        Discription :
            Extracts the real and imaginary parts of an array of complex numbers.
        Parameters:
            complex_array (numpy.ndarray): The array of complex numbers.
        
        Returns:
            Two NumPy arrays containing the real and imaginary parts, respectively.
    """
    real_part = np.real(complex_array)
    imaginary_part = np.imag(complex_array)
    return real_part, imaginary_part
    
def main():
    complex_array = np.array([1+0j, 0.70710678+0.70710678j])
    print("Original array:",complex_array)  
    real_part, imag_part = extract_real_imag_part(complex_array)
    print("Real part of the array:",real_part)
    print("Imaginary part of the array:",imag_part)
if __name__ == "__main__":
    main()    
    

Original array: [1.        +0.j         0.70710678+0.70710678j]
Real part of the array: [1.         0.70710678]
Imaginary part of the array: [0.         0.70710678]


11.Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [13]:
def array_info(arr):
    """
        Discription :
            Returns the number of elements, size of each element in bytes, and the total bytes consumed by the array.
        Parameters:
            arr (numpy.ndarray): The array to analyze.
        
        Returns:
            tuple: (number of elements, size of each element in bytes, total bytes)
    """    
    
    num_elements = arr.size
    elements_size = arr.itemsize
    total_bytes = arr.nbytes
    return num_elements,elements_size,total_bytes
def main():
    array1 = np.array([1,2,3,4,5])
    print("the given array :",array1)
    num_elements,elements_size ,total_bytes = array_info(array1)
    print("Number of Elements in array :",num_elements)
    print("size of the Elements :",elements_size)
    print("total bytes in the array :",total_bytes)

if __name__ == "__main__":
    main()  
       

the given array : [1 2 3 4 5]
Number of Elements in array : 5
size of the Elements : 8
total bytes in the array : 40


12.Python program to find common values between two arrays.

In [14]:
def common_values(arr1,arr2):
    """
        Discription :
            This program find the common values between two arrays
        Parameters:
            arr1 , arr2 : The array to common values
        
        Returns:
            the intersection between two arrays
    """     
    return np.intersect1d(arr1,arr2)
def main():
    array1 = np.array([0,10,20,40,60])
    array2 = np.array([10, 30, 40]) 
    common_value = common_values(array1,array2)
    print("The common values between the two arrays:",common_value)
if __name__ == "__main__":
    main()       

The common values between the two arrays: [10 40]


13.Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

In [15]:
def set_difference(arr1, arr2):
    """
        Discription :
            Finds the set difference between two arrays.
    
        Parameters:
            arr1 (numpy.ndarray): The first input array.
            arr2 (numpy.ndarray): The second input array.
        
        Returns:
            A sorted array of unique values that are in arr1 but not in arr2.
    """
    return np.setdiff1d(arr1, arr2)

def main():
    array1 = np.array([0, 10, 20, 40, 60, 80])
    array2 = np.array([10, 30, 40, 50, 70, 90])
    
    print("Array1:", array1)
    print("Array2:", array2)
    
    result = set_difference(array1, array2)
    
    print("Set difference between two arrays:",result)

if __name__ == "__main__":
    main()


Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70 90]
Set difference between two arrays: [ 0 20 60 80]


14.Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.

In [16]:
def set_exclusive_or(arr1, arr2):
    """
        Discription :
            Finds the set exclusive-or of two arrays.
    
        Parameters:
            arr1 (numpy.ndarray): The first input array.
            arr2 (numpy.ndarray): The second input array.
        
        Returns:
            A sorted array of unique values that are in only one of the input arrays.
    """
    return np.setxor1d(arr1, arr2)

def main():
    array1 = np.array([0, 10, 20, 40, 60, 80])
    array2 = np.array([10, 30, 40, 50, 70])
    
    print("Array1:", array1)
    print("Array2:", array2)
    
    result = set_exclusive_or(array1, array2)
    
    print("Unique values that are in only one (not both) of the input arrays:")
    print(result)

if __name__ == "__main__":
    main()


Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


15.Python program compare two arrays using numpy.

In [17]:
def compare_arrays(arr1, arr2):
    """
        Discription :
            Compares two arrays element-wise and returns the comparison results.
    
        Parameters:
            arr1 (numpy.ndarray): The first input array.
            arr2 (numpy.ndarray): The second input array.
        
        Returns:
            dict: A dictionary containing the results of different comparisons.
    """
    comparison_results = {
        "a > b": arr1 > arr2,
        "a >= b": arr1 >= arr2,
        "a < b": arr1 < arr2,
        "a <= b": arr1 <= arr2
    }
    return comparison_results

def main():
    array_a = np.array([1, 2,3])
    array_b = np.array([4, 5,3])
    
    print("Array a:", array_a)
    print("Array b:", array_b)
    
    results = compare_arrays(array_a, array_b)
    
    for comparison, result in results.items():
        print(comparison)
        print(result)

if __name__ == "__main__":
    main()


Array a: [1 2 3]
Array b: [4 5 3]
a > b
[False False False]
a >= b
[False False  True]
a < b
[ True  True False]
a <= b
[ True  True  True]


16.Python program to create a contiguous flattened array.

In [18]:
def flatten_array(arr):
    """
        Discription :
            Creates a contiguous flattened array.
    
        Parameters:
            arr (numpy.ndarray): The array to flatten.
        
        Returns:
            numpy.ndarray: The flattened array.
    """
    return arr.flatten()

def main():
    array = np.array([[10, 20, 30], [20, 40, 50]])
    
    print("Original array:")
    print(array)
    
    flattened_array = flatten_array(array)
    
    print("New flattened array:")
    print(flattened_array)

if __name__ == "__main__":
    main()


Original array:
[[10 20 30]
 [20 40 50]]
New flattened array:
[10 20 30 20 40 50]


17.Python program to change the data type of an array.

In [19]:
def change_array_dtype(arr, new_dtype):
    """
        Discription :
            Changes the data type of a NumPy array.
    
        Parameters:
            arr (numpy.ndarray): The array whose data type is to be changed.
            new_dtype (str or type): The new data type.
        
        Returns:
            numpy.ndarray: The array with the new data type.
    """
    return arr.astype(new_dtype)

def main():
    array = np.array([[2, 4, 6], [6, 8, 10]])
    
    print("Original array:")
    print(array)
    print("Data type of the array x is:", array.dtype)
    
    new_dtype = np.float64
    array_float = change_array_dtype(array, new_dtype)
    
    print("New Type:", array_float.dtype)
    print(array_float)

if __name__ == "__main__":
    main()


Original array:
[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int64
New Type: float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


18.Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.

In [20]:
def create_identity(size):
    """
        Discription :
            use for identity matrix
    
        Parameters:
            size: its provid the size for identity matrix
        Returns:
            the identity matrix
    """    
    return np.identity(size)
def main():
    size =3
    result = create_identity(size)
    print("The identity matrix is :",result)
if __name__ == "__main__":
    main()        

The identity matrix is : [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19.Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]

In [21]:
def custom_array():
    """
        Discription :
            Creates an array as per the specified pattern:
    
        Parameters:
            None
        Returns:
            The created array.
    """  
    arr = np.zeros((4,3))
    arr[1,0]=1
    arr[2,0:2] = 1
    arr[3,0:]=1
    return arr 
def main():
    result = custom_array()
    print("The custom array is :",result)
if __name__ == "__main__":
    main()        

The custom array is : [[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20.Python program to concatenate two 2-dimensional arrays.

In [22]:
def concatenate_arrays(arr1, arr2):
    """
        Discription :
            Concatenates two 2-dimensional arrays horizontally.
    
        Parameters:
            arr1 : The first 2D array.
            arr2 : The second 2D array.
        
        Returns:
            The concatenated array.
    """
    return np.concatenate((arr1, arr2), axis=1)

def main():
    array1 = np.array([[0, 1, 3], [5, 7, 9]])
    array2 = np.array([[0, 2, 4], [6, 8, 10]])
    
    result = concatenate_arrays(array1, array2)
    
    print("Concatenated array:")
    print(result)

if __name__ == "__main__":
    main()


Concatenated array:
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21.Python program to make an array immutable (read-only).

In [23]:
def make_array_immutable(arr):
    """
        Discription :
            Makes the given NumPy array immutable (read-only).
    
        Parameters:
            arr : The array to be made immutable.
        
        Returns:
            None
    """
    arr.flags.writeable = False

def main():
    x = np.array([1, 2, 3, 4, 5])
    
    print("Original array:")
    print(x)
    
    make_array_immutable(x)
    
    print("\nTest the array is read-only or not:")
    try:
        x[0] = 10
    except ValueError as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()


Original array:
[1 2 3 4 5]

Test the array is read-only or not:
Error: assignment destination is read-only


22.Python program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.

In [24]:
def multiply_elemnts(arr,mul):
    """
        Discription :
            Multiplies every element of the given array by the specified multiplier.
    
        Parameters:
            arr: The input array.
            
        Returns:
            The array with elements multiplied by the multiplier.
    """
    return arr*mul
def main():
    arr = np.arange(12).reshape(3,4)
    print("original array \n",arr)
    new_arr = multiply_elemnts(arr,3)
    print("update array \n",new_arr)
if __name__ == "__main__":
    main()    



original array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
update array 
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23.Python program to convert a NumPy array into Python list structure

In [25]:
def array_to_list(arr):
    """
        Discription :
            Converts a NumPy array into a Python list structure.
    
        Parameters:
            arr : The input NumPy array.
        
        Returns:
            list: The converted Python list.
    """
    return arr.tolist()

def main():
    array = np.array([[0, 1], [2, 3], [4, 5]])
    
    print("Original array elements:\n",array)
    
    
    list_structure = array_to_list(array)
    
    print("\nArray to list:\n",list_structure)
   

if __name__ == "__main__":
    main()


Original array elements:
 [[0 1]
 [2 3]
 [4 5]]

Array to list:
 [[0, 1], [2, 3], [4, 5]]


24.Python program to convert a NumPy array into Python list structure(precision = 3)

In [26]:
def array_to_list_with_precision(arr, precision=3):
    """
        Discription :
            Rounds the values in a NumPy array to the specified precision and converts it into a Python list.
    
        Parameters:
            arr : The input NumPy array.
            precision : The number of decimal places to round the array values.
        
        Returns:
            list: The converted Python list with rounded values.
    """
    rounded_arr = np.round(arr, precision)
    
    list_structure = rounded_arr.tolist()
    
    return list_structure

def main():
    array = np.random.rand(10)
    
    print("Original array elements:\n")
    print(array)
    
    list_structure = array_to_list_with_precision(array)
    
    print("\nArray with precision 3:\n")
    print(list_structure)

if __name__ == "__main__":
    main()


Original array elements:

[0.84055004 0.8273868  0.29299217 0.7428252  0.07363028 0.87373735
 0.20665545 0.62402267 0.11282014 0.29331198]

Array with precision 3:

[0.841, 0.827, 0.293, 0.743, 0.074, 0.874, 0.207, 0.624, 0.113, 0.293]


25.Python program to suppresses the use of scientific notation for small numbers in numpy array

In [28]:
def suppress_scientific_notation(arr, precision=3):
    """
        Discription :
            Suppresses the use of scientific notation in the NumPy array and prints the array with the specified precision.
    
        Parameters:
            arr : The input NumPy array.
            precision : The number of decimal places to round the array values.
        return:
            None    
    """
    np.set_printoptions(suppress=True, precision=precision)
    
    print("Array with precision :".format(precision))
    print(arr)

def main():
    array = np.array([1.6e-10, 1.6, 1200, 0.235])
    
    print("Original array elements:")
    print(array)
    
    suppress_scientific_notation(array)

if __name__ == "__main__":
    main()


Original array elements:
[   0.       1.6   1200.       0.235]
Array with precision :
[   0.       1.6   1200.       0.235]


26.Python program to how to add an extra column to an numpy array.

In [30]:
def add_column(arr, new_column):
    """
        Discription :
            Adds a new column to a 2D NumPy array.
    
        Parameters:
            arr : The original 2D array.
            new_column : The new column to be added.
        
        Returns:
            The new array with the extra column.
    """
    return np.column_stack((arr, new_column))

def main():
    array = np.array([[10, 20, 30], [40, 50, 60]])
    new_column = np.array([100, 200])
    
    print("Original array:")
    print(array)
    
    result = add_column(array, new_column)
    
    print("\nArray after adding a new column:")
    print(result)

if __name__ == "__main__":
    main()


Original array:
[[10 20 30]
 [40 50 60]]

Array after adding a new column:
[[ 10  20  30 100]
 [ 40  50  60 200]]


27.Python program to remove specific elements in a numpy array.

In [32]:
def remove_elements(arr, indices):
    """
        Discription :
            Removes elements from a NumPy array at the specified indices.
    
        Parameters:
            arr : The original array.
            indices : The indices of the elements to be removed.
        
        Returns:
            The array with the specified elements removed.
    """
    return np.delete(arr, indices)

def main():
    array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
    
    print("Original array:")
    print(array)
    
    indices_to_remove = [0, 3, 4]
    result = remove_elements(array, indices_to_remove)
    
    print("\nArray after removing elements at indices 0, 3, and 4:")
    print(result)

if __name__ == "__main__":
    main()


Original array:
[ 10  20  30  40  50  60  70  80  90 100]

Array after removing elements at indices 0, 3, and 4:
[ 20  30  60  70  80  90 100]
